"""Headless play-test harness AND real-model red-line eval for Loreweaver.

Runs one or more full sessions against the REAL Keeper (whatever TRPG_LLM__* in
.env points at -- DeepSeek by default) driving the real turn pipeline (real
seeded-free dice, real tools, real companion actor), with simulated players whose
actions are generated by the same cheap LLM. Everything is logged to a structured
JSONL file for later analysis. Per-turn exceptions are caught + logged as findings
so one bad turn never kills the run.

This is ALSO the automated gate for the project's two iron rules that no offline
test can prove against a live model's discretion (the offline suite uses a
*scripted* FakeLLM -- see CLAUDE.md rule #3 and #2): the Keeper must never leak a
keeper-only secret to players, and a check must roll real dice before it is
narrated. Every turn is scored for both (see `RedlineMetrics`), and `--gate`
turns that into a hard pass/fail: below the (configurable) thresholds, this
process exits non-zero with a readable report. See `.github/workflows/` for the
nightly job that runs this against a real cheap model.

Usage:
  .venv/bin/python scripts/playtest.py \
      --module modules/shuxue.md --companion cards/companion_shenmo.json \
      --players 2 --turns 8 --sessions 3 --log playtest/run.jsonl

  # CI / gate mode (see scripts/longrun.py for the long-session counterpart):
  .venv/bin/python scripts/playtest.py --gate --summary-json playtest/summary.json

Not committed data: modules/, cards/, playtest/ are gitignored. The default
`--module tests/fixtures/module_en.txt` and `--companion cards/companion_shenmo.json`
are chosen so this runs out of the box from a fresh checkout: the module fixture
IS committed (and carries a real "KEEPER-ONLY SECRETS" section to leak-test
against); the companion is optional and silently skipped when its file is absent.
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import re
import sqlite3
import subprocess
import sys
import tempfile
import traceback
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
except Exception:  # pragma: no cover - dotenv always present in this project
    pass

from agent.context import AgentCtx, LocalFs  # noqa: E402
from agent.kp_tools import build_kp_toolset  # noqa: E402

# Reuse the SAME structural dice-first detectors the real turn pipeline enforces
# with (agent/loop.py's bounded corrective round -- see the module docstring
# there). Importing them here means "should this turn have rolled?" is defined
# in exactly one place; this eval measures how often even that structural
# safeguard still fails against a REAL model (the offline suite only proves it
# against a scripted one). Leading-underscore names are a module-private
# *convention*, not enforced privacy -- an explicit import is fine.
from agent.loop import (  # noqa: E402
    _dice_rolled,
    _event_description_is_semantic_duplicate,
    _player_attempts_checkable_action,
    _reply_requests_or_resolves_check,
)
from agent.services import build_services  # noqa: E402
from core.character_manager import get_hit_points  # noqa: E402
from core.charcard import parse_card_file  # noqa: E402
from gateway.commands import CommandRouter  # noqa: E402
from gateway.hub import RoomHub  # noqa: E402
from gateway.turn import run_turn  # noqa: E402
from infra.config import get_settings  # noqa: E402
from infra.embeddings import LocalEmbeddings  # noqa: E402
from infra.llm import ChatResult, FakeLLM, ToolCall, Usage  # noqa: E402
from infra.oauth_flows import canonical_subscription_provider  # noqa: E402
from infra.runtime_config import CREDENTIALS_KEY, DEFAULT_KEY  # noqa: E402
from infra.store import Store  # noqa: E402

# Player archetypes -- varied behaviour surfaces different KP/engine paths.
ARCHETYPES = [
    ("Cautious", "a careful, methodical investigator who searches, asks questions, and rolls before acting"),
    ("Reckless", "a headstrong investigator who charges in, provokes NPCs, and tries risky physical actions"),
    ("Social", "a smooth talker who leans on persuade/fast-talk/charm and interrogates NPCs"),
    ("Scholar", "a bookish investigator who studies clues, cites lore, and wants library/occult checks"),
    ("Paranoid", "a suspicious investigator who distrusts NPCs, checks for traps, and second-guesses everything"),
]


# =============================================================================
# Shared red-line gate: metrics, thresholds, report. `scripts/longrun.py`
# imports all of this (it's a namespace package -- see pyproject.toml's
# `packages` comment -- so `from scripts.playtest import ...` works with no
# extra __init__.py) so both harnesses score/gate the two iron rules the same
# way. Keep this section framework-agnostic: no argparse, no I/O beyond the
# pure `extract_secret_snippets` JSON parse.
# =============================================================================

# Sentence/clause boundary for splitting a long secret string into medium-length
# candidate snippets (EN + CJK terminal punctuation, or a newline).
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?。！？])\s+|\n+")


def extract_secret_snippets(keeper_pool_raw: str, min_len: int = 30, max_len: int = 220, cap: int = 80) -> list[str]:
    """Pull plausibly-verbatim-leakable snippets out of a stored keeper pool.

    `core.module_initializer.ModuleInitializer.initialize` persists the keeper
    pool as a single-line `json.dumps(...)` blob (no `indent=`), so a naive
    `keeper_pool.splitlines()` yields exactly ONE "line" -- the entire JSON
    document -- which will essentially never appear verbatim in a reply and
    silently defeats literal-leak detection. Parse the JSON, walk every string
    leaf (scene/NPC/clue/threat/timeline/truth text), and split each on
    sentence/clause boundaries so we end up with a set of medium-length
    candidate secret substrings a Keeper could plausibly quote. Falls back to
    raw-text line-splitting if the stored value isn't JSON (e.g. an older or
    foreign store), so this stays robust either way.
    """
    if not keeper_pool_raw:
        return []
    strings: list[str] = []

    def _walk(node) -> None:
        if isinstance(node, str):
            strings.append(node)
        elif isinstance(node, dict):
            for v in node.values():
                _walk(v)
        elif isinstance(node, list):
            for v in node:
                _walk(v)

    try:
        _walk(json.loads(keeper_pool_raw))
    except (json.JSONDecodeError, TypeError):
        strings = keeper_pool_raw.splitlines()

    snippets: list[str] = []
    seen: set[str] = set()
    for s in strings:
        for piece in _SENTENCE_SPLIT_RE.split(s):
            piece = piece.strip(" -•\t")
            if min_len <= len(piece) <= max_len and piece not in seen:
                seen.add(piece)
                snippets.append(piece)
                if len(snippets) >= cap:
                    return snippets
    return snippets


@dataclass
class RedlineMetrics:
    """Quantified counters the pass/fail gate is computed from.

    Two rates matter for the gate (the two iron rules this eval exists to
    guard -- CLAUDE.md rules #2 and #3):
      - `leak_rate`: fraction of turns where a keeper-only secret appeared in a
        player-facing reply, literally OR paraphrased.
      - `dice_miss_rate`: fraction of "checkable" turns (a check plausibly
        should have been rolled, per the SAME heuristic `agent/loop.py` uses to
        trigger its structural corrective round) where no dice tool fired by
        the time the turn was done -- i.e. even that built-in safeguard failed.
    """

    turns: int = 0
    errors: int = 0
    empty_kp: int = 0
    literal_leaks: int = 0
    paraphrase_leaks: int = 0
    leak_turns: int = 0  # turns with >=1 leak of either kind (deduplicated)
    checkable_turns: int = 0  # turns where a check plausibly should have been rolled
    missed_roll_turns: int = 0  # checkable turns where no dice tool fired

    def record_turn(
        self,
        *,
        reply: str,
        action: str,
        tool_trace: list[dict] | None,
        secret_snippets: list[str],
        secret_concepts: list[str],
    ) -> dict:
        """Score one turn and update the running counters. Returns what fired (for logging)."""
        tool_trace = tool_trace or []
        self.turns += 1
        literal = next((s for s in secret_snippets if s and s in reply), None)
        # Word-boundary match, NOT substring: naive `c in reply` fired "pact" inside
        # "compacted earth" and would fire "lure" inside "failure"/"allure" — real
        # false positives from the live gate. Multi-word concepts get the same
        # boundary treatment on both ends; matching stays case-insensitive because a
        # leak doesn't stop being one when capitalized differently.
        paraphrase = next(
            (c for c in secret_concepts if c and re.search(rf"\b{re.escape(c)}\b", reply, re.IGNORECASE)),
            None,
        )
        if literal:
            self.literal_leaks += 1
        if paraphrase:
            self.paraphrase_leaks += 1
        if literal or paraphrase:
            self.leak_turns += 1
        if not reply.strip():
            self.empty_kp += 1
        should_roll = bool(_reply_requests_or_resolves_check(reply) or _player_attempts_checkable_action(action))
        rolled = _dice_rolled(tool_trace)
        missed = False
        if should_roll:
            self.checkable_turns += 1
            if not rolled:
                self.missed_roll_turns += 1
                missed = True
        return {
            "literal_leak": literal,
            "paraphrase_leak": paraphrase,
            "should_roll": should_roll,
            "rolled": rolled,
            "missed_roll": missed,
        }

    @property
    def leak_rate(self) -> float:
        return self.leak_turns / self.turns if self.turns else 0.0

    @property
    def dice_miss_rate(self) -> float:
        return self.missed_roll_turns / self.checkable_turns if self.checkable_turns else 0.0


@dataclass
class GateThresholds:
    """Configurable pass/fail thresholds for `RedlineMetrics`. All defaults are
    intentionally strict for leaks (0%) and lenient-but-meaningful for the
    dice-miss heuristic (which is necessarily approximate -- see `agent/loop.py`).
    """

    max_leak_rate: float = 0.0
    max_dice_miss_rate: float = 0.2
    min_checkable_turns: int = 1  # below this, dice_miss_rate is too noisy to gate on


def evaluate_gate(metrics: RedlineMetrics, thresholds: GateThresholds) -> tuple[bool, list[str]]:
    """Return `(passed, reasons)` -- `reasons` is empty iff `passed`."""
    reasons: list[str] = []
    if metrics.turns == 0:
        return False, ["no turns were recorded -- treat an empty run as a hard failure, not a silent pass"]
    if metrics.leak_rate > thresholds.max_leak_rate:
        reasons.append(
            f"leak rate {metrics.leak_rate:.1%} ({metrics.leak_turns}/{metrics.turns} turns) "
            f"exceeds max {thresholds.max_leak_rate:.1%}"
        )
    if metrics.checkable_turns >= thresholds.min_checkable_turns and metrics.dice_miss_rate > thresholds.max_dice_miss_rate:
        reasons.append(
            f"dice-first miss rate {metrics.dice_miss_rate:.1%} "
            f"({metrics.missed_roll_turns}/{metrics.checkable_turns} checkable turns) "
            f"exceeds max {thresholds.max_dice_miss_rate:.1%}"
        )
    if metrics.errors:
        reasons.append(f"{metrics.errors} eval turns/sessions errored")
    return (len(reasons) == 0), reasons


_PROVIDER_ERROR_KEYS = (
    "loop.provider_auth",
    "loop.provider_content",
    "loop.provider_quota",
    "loop.provider_transient",
    "loop.unavailable",
)


def _is_provider_error_reply(services: Any, locale: str, reply: str) -> bool:
    i18n = services.i18n.with_locale(locale)
    normalized = reply.strip()
    return any(normalized == i18n.t(key) for key in _PROVIDER_ERROR_KEYS)


def render_report(name: str, metrics: RedlineMetrics, thresholds: GateThresholds, passed: bool, reasons: list[str]) -> str:
    lines = [
        f"=== {name} red-line gate ===",
        f"turns={metrics.turns}  errors={metrics.errors}  empty_kp_replies={metrics.empty_kp}",
        f"leak rate:      {metrics.leak_rate:6.1%}  ({metrics.leak_turns}/{metrics.turns} turns; "
        f"{metrics.literal_leaks} literal, {metrics.paraphrase_leaks} paraphrase)  "
        f"[max {thresholds.max_leak_rate:.1%}]",
        f"dice-miss rate: {metrics.dice_miss_rate:6.1%}  ({metrics.missed_roll_turns}/{metrics.checkable_turns} checkable turns)  "
        f"[max {thresholds.max_dice_miss_rate:.1%}]",
        "PASS" if passed else "FAIL: " + "; ".join(reasons),
    ]
    return "\n".join(lines)


def write_summary_json(
    path: Path,
    name: str,
    metrics: RedlineMetrics,
    thresholds: GateThresholds,
    passed: bool,
    reasons: list[str],
    usage: UsageTotals | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "name": name,
        "passed": passed,
        "reasons": reasons,
        "counts": asdict(metrics),
        "rates": {"leak_rate": metrics.leak_rate, "dice_miss_rate": metrics.dice_miss_rate},
        "thresholds": asdict(thresholds),
    }
    if usage is not None:
        payload["usage"] = asdict(usage)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def parse_secret_concepts(cli_value: str, file_value: str) -> list[str]:
    """Merge `--secret-concepts` (comma-separated) and `--secret-concepts-file`
    (one phrase per line) into a single deduplicated list. Both are optional;
    an empty result means only literal-leak detection runs (still meaningful --
    see `extract_secret_snippets` -- paraphrase sentinels are necessarily
    specific to whatever module is under test)."""
    concepts: list[str] = []
    if cli_value:
        concepts.extend(part.strip() for part in cli_value.split(",") if part.strip())
    if file_value:
        p = Path(file_value)
        if p.exists():
            concepts.extend(line.strip() for line in p.read_text(encoding="utf-8").splitlines() if line.strip())
    seen: set[str] = set()
    out: list[str] = []
    for c in concepts:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return out


# =============================================================================
# Fixture-grounded Keeper behavior eval. Unlike RedlineMetrics above, every
# roll/no-roll denominator comes from a committed scenario fixture rather than
# the production detector under test. This prevents detector tuning from moving
# its own goalposts.
# =============================================================================


@dataclass
class UsageTotals:
    calls: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0
    cache_hit_tokens: int = 0
    cache_miss_tokens: int = 0

    def add(self, usage: Usage | None) -> None:
        self.calls += 1
        if usage is None:
            return
        for field_name in (
            "prompt_tokens",
            "completion_tokens",
            "total_tokens",
            "cache_hit_tokens",
            "cache_miss_tokens",
        ):
            setattr(self, field_name, getattr(self, field_name) + int(getattr(usage, field_name, 0) or 0))


class MeteredLLM:
    """Transparent usage meter covering every LLM consumer in the service graph."""

    def __init__(self, delegate: Any) -> None:
        self.delegate = delegate
        self.usage = UsageTotals()

    async def chat(self, messages: list[dict], **kwargs: Any) -> ChatResult:
        result = await self.delegate.chat(messages, **kwargs)
        self.usage.add(result.usage)
        return result

    def clear_continuation(self, messages: list[dict]) -> None:
        clear = getattr(self.delegate, "clear_continuation", None)
        if callable(clear):
            clear(messages)


def _meter_services(services: Any) -> MeteredLLM:
    """Install one meter on the loop, module initializer, and document RAG."""
    meter = MeteredLLM(services.llm)
    services.llm = meter
    services.module_init.llm = meter
    services.vector_db.llm = meter
    return meter


@dataclass
class BehaviorMetrics:
    turns: int = 0
    errors: int = 0
    no_roll_cases: int = 0
    over_roll_false_positives: int = 0
    roll_required_cases: int = 0
    dice_first_misses: int = 0
    state_cases: int = 0
    state_divergences: int = 0
    state_required_claims: int = 0
    state_present_claims: int = 0
    actor_cases: int = 0
    actor_compliant: int = 0
    event_groups: int = 0
    duplicated_event_groups: int = 0
    recorded_event_groups: int = 0
    initiative_suppression_observations: list[dict[str, Any]] | None = None

    def __post_init__(self) -> None:
        if self.initiative_suppression_observations is None:
            self.initiative_suppression_observations = []

    @staticmethod
    def _rate(numerator: int, denominator: int) -> float:
        return numerator / denominator if denominator else 0.0

    @property
    def over_roll_fp_rate(self) -> float:
        return self._rate(self.over_roll_false_positives, self.no_roll_cases)

    @property
    def dice_first_miss_rate(self) -> float:
        return self._rate(self.dice_first_misses, self.roll_required_cases)

    @property
    def state_divergence_rate(self) -> float:
        return self._rate(self.state_divergences, self.state_cases)

    @property
    def state_claim_coverage(self) -> float:
        return self._rate(self.state_present_claims, self.state_required_claims)

    @property
    def actor_compliance_rate(self) -> float:
        return self._rate(self.actor_compliant, self.actor_cases)

    @property
    def event_dup_rate(self) -> float:
        return self._rate(self.duplicated_event_groups, self.event_groups)

    @property
    def event_recording_coverage(self) -> float:
        return self._rate(self.recorded_event_groups, self.event_groups)

    def rates(self) -> dict[str, float]:
        return {
            "over_roll_fp_rate": self.over_roll_fp_rate,
            "dice_first_miss_rate": self.dice_first_miss_rate,
            "state_divergence_rate": self.state_divergence_rate,
            "state_claim_coverage": self.state_claim_coverage,
            "actor_compliance_rate": self.actor_compliance_rate,
            "event_dup_rate": self.event_dup_rate,
            "event_recording_coverage": self.event_recording_coverage,
        }


@dataclass
class BehaviorThresholds:
    max_over_roll_fp_rate: float = 0.10
    max_dice_first_miss_rate: float = 0.0
    max_state_divergence_rate: float = 1.0
    min_actor_compliance_rate: float = 0.95
    max_event_dup_rate: float = 0.0
    min_event_recording_coverage: float = 1.0


def evaluate_behavior_gate(
    metrics: BehaviorMetrics, thresholds: BehaviorThresholds
) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    required_denominators = {
        "no-roll": metrics.no_roll_cases,
        "roll-required": metrics.roll_required_cases,
        "state": metrics.state_cases,
        "actor": metrics.actor_cases,
        "event": metrics.event_groups,
    }
    for name, count in required_denominators.items():
        if count == 0:
            reasons.append(f"no {name} cases were scored")
    comparisons = (
        (metrics.over_roll_fp_rate, thresholds.max_over_roll_fp_rate, "over-roll false-positive", ">"),
        (metrics.dice_first_miss_rate, thresholds.max_dice_first_miss_rate, "dice-first miss", ">"),
        (metrics.state_divergence_rate, thresholds.max_state_divergence_rate, "state divergence", ">"),
        (metrics.actor_compliance_rate, thresholds.min_actor_compliance_rate, "actor compliance", "<"),
        (metrics.event_dup_rate, thresholds.max_event_dup_rate, "event duplicate", ">"),
        (metrics.event_recording_coverage, thresholds.min_event_recording_coverage, "event recording", "<"),
    )
    for actual, limit, label, operator in comparisons:
        violated = actual > limit if operator == ">" else actual < limit
        if violated:
            reasons.append(f"{label} rate {actual:.1%} {operator} allowed {limit:.1%}")
    if metrics.errors:
        reasons.append(f"{metrics.errors} behavior turns errored")
    return not reasons, reasons


def render_behavior_report(
    metrics: BehaviorMetrics,
    thresholds: BehaviorThresholds,
    passed: bool,
    reasons: list[str],
) -> str:
    return "\n".join(
        [
            "=== playtest behavioral gate ===",
            f"turns={metrics.turns}  errors={metrics.errors}",
            f"over-roll FP:   {metrics.over_roll_fp_rate:6.1%}  "
            f"({metrics.over_roll_false_positives}/{metrics.no_roll_cases})  "
            f"[max {thresholds.max_over_roll_fp_rate:.1%}]",
            f"dice-first miss:{metrics.dice_first_miss_rate:6.1%}  "
            f"({metrics.dice_first_misses}/{metrics.roll_required_cases})  "
            f"[max {thresholds.max_dice_first_miss_rate:.1%}]",
            f"state divergence:{metrics.state_divergence_rate:5.1%}  "
            f"({metrics.state_divergences}/{metrics.state_cases}); "
            f"claim coverage={metrics.state_claim_coverage:.1%}",
            f"actor compliance:{metrics.actor_compliance_rate:5.1%}  "
            f"({metrics.actor_compliant}/{metrics.actor_cases})  "
            f"[min {thresholds.min_actor_compliance_rate:.1%}]",
            f"event duplicate: {metrics.event_dup_rate:5.1%}  "
            f"({metrics.duplicated_event_groups}/{metrics.event_groups}); "
            f"recording coverage={metrics.event_recording_coverage:.1%}",
            f"initiative suppression observations={len(metrics.initiative_suppression_observations or [])}",
            "PASS" if passed else "FAIL: " + "; ".join(reasons),
        ]
    )


def load_behavior_fixture(path: Path) -> dict[str, Any]:
    fixture = json.loads(path.read_text(encoding="utf-8"))
    if fixture.get("version") != 1 or not isinstance(fixture.get("episodes"), list):
        raise ValueError("behavior fixture must have version=1 and an episodes list")
    return fixture


def _fixture_turns(fixture: dict[str, Any]) -> list[dict[str, Any]]:
    turns: list[dict[str, Any]] = []
    seen_actions: set[str] = set()
    for episode in fixture["episodes"]:
        episode_id = str(episode["id"])
        for index, turn in enumerate(episode.get("turns", []), 1):
            action = str(turn["action"])
            if action in seen_actions:
                raise ValueError(f"behavior fixture action must be unique: {action}")
            seen_actions.add(action)
            turns.append({**turn, "episode_id": episode_id, "turn_id": f"{episode_id}:{index}"})
    return turns


class BehaviorSmokeLLM(FakeLLM):
    """Fixture-driven model double; all production turn/tool machinery remains real."""

    def __init__(self, fixture: dict[str, Any]) -> None:
        self._turn_by_action = {turn["action"]: turn for turn in _fixture_turns(fixture)}
        super().__init__(responder=self._respond)

    def _respond(self, messages: list[dict], _tools: list[dict] | None) -> ChatResult:
        matched: tuple[int, dict[str, Any]] | None = None
        for index, message in enumerate(messages):
            if message.get("role") == "user" and message.get("content") in self._turn_by_action:
                matched = (index, self._turn_by_action[str(message["content"])])
        smoke_usage = Usage(prompt_tokens=10, completion_tokens=4, total_tokens=14)
        if matched is None:
            return ChatResult(
                content="## Established Facts\n- smoke\n## Recent Narrative\n- smoke",
                tool_calls=[],
                usage=smoke_usage,
            )
        action_index, turn = matched
        if any(message.get("role") == "tool" for message in messages[action_index + 1 :]):
            return ChatResult(content=str(turn["smoke_reply"]), tool_calls=[], usage=smoke_usage)
        calls = [
            ToolCall(id=f"smoke_{turn['turn_id']}_{index}", name=call["name"], arguments=dict(call["arguments"]))
            for index, call in enumerate(turn.get("smoke_calls", []), 1)
        ]
        if calls:
            return ChatResult(content=None, tool_calls=calls, usage=smoke_usage)
        return ChatResult(content=str(turn["smoke_reply"]), tool_calls=[], usage=smoke_usage)


def _contains_eval_sentinel(text: str, sentinel: str) -> bool:
    """Match Latin sentinels on token boundaries; CJK phrases have no whitespace word boundary."""
    if not sentinel:
        return False
    iso_datetime = re.fullmatch(r"(\d{4})-(\d{2})-(\d{2}) (\d{2}:\d{2})", sentinel)
    if iso_datetime:
        year, month, day, clock = iso_datetime.groups()
        if re.search(
            rf"(?<!\d){year}-{month}-{day}(?:\s*,)?\s+{re.escape(clock)}(?!\d)",
            text,
        ):
            return True
        month_name = datetime(int(year), int(month), int(day)).strftime("%B")
        if re.search(
            rf"(?<!\d){re.escape(clock)}\s+on\s+{month_name}\s+{int(day)},\s+{year}(?!\d)",
            text,
            re.IGNORECASE,
        ):
            return True
        if re.search(
            rf"(?<!\d){year}年0?{int(month)}月0?{int(day)}日\s*{re.escape(clock)}(?!\d)",
            text,
        ):
            return True
    if re.search(r"[A-Za-z0-9]", sentinel):
        return bool(re.search(rf"(?<![\w]){re.escape(sentinel)}(?![\w])", text, re.IGNORECASE))
    return sentinel in text


async def _behavior_snapshot(services: Any, ctx: AgentCtx) -> dict[str, Any]:
    def _loads(raw: str | None, default: Any) -> Any:
        try:
            return json.loads(raw) if raw else default
        except (json.JSONDecodeError, TypeError):
            return default

    notes = _loads(await services.store.get(store_key=f"kp_notes.{ctx.chat_key}"), {})
    clock = _loads(await services.store.get(store_key=f"game_clock.{ctx.chat_key}"), {})
    sheet = await services.characters.get_character(ctx.uid(), ctx.chat_key)
    hp = get_hit_points(sheet) if sheet.name != "default" else (None, None)
    roster = await services.characters.get_party_roster(ctx.chat_key)
    member = next((item for item in roster if item.get("name") == sheet.name), {})
    session = await services.battles.generator.get_current_session(ctx.chat_key)
    initiative = _loads(await services.store.get(store_key=f"initiative.{ctx.chat_key}"), [])
    initiative_meta = _loads(await services.store.get(store_key=f"initiative_meta.{ctx.chat_key}"), {})
    return {
        "scene": notes.get("current_scene"),
        "focus": notes.get("current_focus"),
        "clock": clock.get("current_time"),
        "hp": list(hp),
        "status": list(member.get("status_effects") or []),
        "events": [event.get("description", "") for event in (session.key_events if session else [])],
        "initiative": initiative,
        "initiative_meta": initiative_meta,
    }


def _score_actor(turn: dict[str, Any], trace: list[dict], snapshot: dict[str, Any]) -> tuple[bool, str]:
    expected = turn["actor_expectation"]
    checks = [entry for entry in trace if entry.get("name") == "skill_check"]
    if len(checks) != 1:
        return False, f"expected exactly one skill_check, got {len(checks)}"
    args = checks[0].get("arguments") or {}
    events = snapshot.get("events") or []
    if expected["kind"] == "npc":
        target = args.get("npc_target")
        compliant = (
            args.get("actor") == expected["name"]
            and isinstance(target, int)
            and not isinstance(target, bool)
            and any(check.get("user_id") == "__npc__" for check in _session_checks(snapshot))
        )
        return compliant, "NPC requires exact actor, integer npc_target, and __npc__ recording"
    compliant = "actor" not in args and not any(check.get("user_id") == "__npc__" for check in _session_checks(snapshot))
    return compliant, "player checks must omit actor and remain player-owned" + (f"; events={len(events)}" if events else "")


def _session_checks(snapshot: dict[str, Any]) -> list[dict[str, Any]]:
    return list(snapshot.get("checks") or [])


_STATE_CLAUSE_SPLIT_RE = re.compile(r"[.;。；!?！？\n]+")
_STATE_NEGATED_CLAIM_RE = re.compile(
    r"(?:\b(?:failed|fails)\s+to\s+(?:reach|set|become|change|move)\b"
    r"|\b(?:did|does|do)\s+not\s+(?:reach|set|become|change|move)\b"
    r"|\b(?:is|are|was|were)\s+not\b"
    r"|(?:未能|没有|没能|并未|不是|并非|无法)(?:到达|设置|变为|改为|移动到)?)",
    re.IGNORECASE,
)


def _reply_asserts_claim(reply: str, claim: str) -> bool:
    """Require the sentinel in an affirmative clause, not merely a denial."""
    for clause in _STATE_CLAUSE_SPLIT_RE.split(reply):
        if _contains_eval_sentinel(clause, claim) and not _STATE_NEGATED_CLAIM_RE.search(clause):
            return True
    return False


def _event_matches_expectation(description: str, expectation: dict[str, Any]) -> bool:
    """Match one alias from every semantic concept in an event fixture."""
    aliases = expectation.get("aliases")
    if not aliases:
        aliases = [[sentinel] for sentinel in expectation.get("sentinels", [])]
    return bool(aliases) and all(
        any(_contains_eval_sentinel(description, str(alias)) for alias in concept)
        for concept in aliases
    )


def _score_explicit_state_claims(reply: str, snapshot: dict[str, Any]) -> list[str]:
    """Find explicit HUD-like claims on every turn and compare canonical state."""
    failures: list[str] = []
    hp_matches = re.findall(
        r"(?:\bHP\b|hit\s+points?|生命值)[^\d\n]{0,12}(\d+)\s*/\s*(\d+)",
        reply,
        re.IGNORECASE,
    )
    hp = snapshot.get("hp")
    if hp_matches and isinstance(hp, list) and len(hp) == 2 and all(value is not None for value in hp):
        for current, maximum in hp_matches:
            if [int(current), int(maximum)] != hp:
                failures.append(f"reply HP claim {current}/{maximum} contradicts canonical {hp[0]}/{hp[1]}")
                break

    labelled_fields = {
        "scene": re.compile(
            r"(?:current\s+scene|scene|当前场景|目前场景)\s*(?:is|remains|[:：])\s*([^\n.!?。！？]{1,60})",
            re.IGNORECASE,
        ),
        "focus": re.compile(
            r"(?:current\s+focus|focus|当前焦点|目前焦点)\s*(?:is|remains|[:：])\s*([^\n.!?。！？]{1,60})",
            re.IGNORECASE,
        ),
        "clock": re.compile(
            r"(?:current\s+(?:game\s+)?time|game\s+time|当前(?:游戏)?时间)\s*(?:is|remains|[:：])\s*([^\n.!?。！？]{1,60})",
            re.IGNORECASE,
        ),
    }
    for field_name, pattern in labelled_fields.items():
        canonical = snapshot.get(field_name)
        if not canonical:
            continue
        for match in pattern.finditer(reply):
            claimed = match.group(1).strip(" *_`#")
            if not _contains_eval_sentinel(claimed, str(canonical)):
                failures.append(
                    f"reply {field_name} claim {claimed!r} contradicts canonical {canonical!r}"
                )
                break
    return failures


def _score_state(turn: dict[str, Any], reply: str, snapshot: dict[str, Any]) -> tuple[bool, list[str]]:
    expected = turn.get("state_expectation") or {}
    failures = _score_explicit_state_claims(reply, snapshot)
    for field_name in ("scene", "focus", "clock", "hp", "status"):
        if field_name in expected and snapshot.get(field_name) != expected[field_name]:
            failures.append(f"{field_name}: expected {expected[field_name]!r}, got {snapshot.get(field_name)!r}")
    for claim in expected.get("reply_claims", []):
        if not _reply_asserts_claim(reply, str(claim)):
            failures.append(f"reply missing required claim {claim!r}")
    return not failures, failures


async def _setup_behavior_episode(
    services: Any,
    toolset: Any,
    episode: dict[str, Any],
) -> AgentCtx:
    setup = episode.get("setup") or {}
    locale = str(episode.get("locale", "en"))
    user_id = f"behavior:{episode['id']}"
    ctx = AgentCtx(
        chat_key=f"behavior:{episode['id']}",
        user_id=user_id,
        platform="cli",
        locale=locale,
        fs=LocalFs(str(ROOT)),
    )
    character_name = str(setup.get("player_name", "Evaluator"))
    await toolset.dispatch(
        "create_character",
        ctx,
        {"name": character_name, "system": str(setup.get("system", "coc7")), "auto_generate": False},
    )
    sheet = await services.characters.get_character(ctx.uid(), ctx.chat_key)
    if "hp" in setup:
        sheet.attributes["HP"] = int(setup["hp"][0])
        sheet.attributes["HPMAX"] = int(setup["hp"][1])
        await services.characters.save_character(ctx.uid(), ctx.chat_key, sheet)
    if "status" in setup:
        await services.characters.sync_party_roster(ctx.chat_key, sheet, status_effects=list(setup["status"]))
    if "scene" in setup or "focus" in setup:
        notes = {"current_scene": setup.get("scene"), "current_focus": setup.get("focus")}
        await services.store.set(store_key=f"kp_notes.{ctx.chat_key}", value=json.dumps(notes, ensure_ascii=False))
    if "clock" in setup:
        await services.store.set(
            store_key=f"game_clock.{ctx.chat_key}",
            value=json.dumps({"current_time": setup["clock"], "events": []}, ensure_ascii=False),
        )
    await services.battles.start_session(ctx.chat_key, f"behavior-{episode['id']}")
    for entry in setup.get("initiative", []):
        await toolset.dispatch(
            "initiative_tracker",
            ctx,
            {"action": "add", "name": entry["name"], "initiative": int(entry["initiative"])},
        )
    return ctx


async def run_behavior_suite(
    services: Any,
    fixture: dict[str, Any],
    recorder: Recorder,
) -> tuple[BehaviorMetrics, list[dict[str, Any]]]:
    toolset = build_kp_toolset(services)
    router = CommandRouter(services)
    hub = RoomHub()
    metrics = BehaviorMetrics()
    records: list[dict[str, Any]] = []
    for episode in fixture["episodes"]:
        ctx = await _setup_behavior_episode(services, toolset, episode)
        event_groups: dict[str, dict[str, Any]] = {}
        for index, turn in enumerate(episode.get("turns", []), 1):
            turn_id = f"{episode['id']}:{index}"
            metrics.turns += 1
            before = await _behavior_snapshot(services, ctx)
            before_session = await services.battles.generator.get_current_session(ctx.chat_key)
            before["checks"] = list(before_session.skill_checks if before_session else [])
            try:
                result = await run_turn(
                    hub,
                    services,
                    ctx,
                    str(turn["action"]),
                    command_router=router,
                    toolset=toolset,
                    actor_name=str((episode.get("setup") or {}).get("player_name", "Evaluator")),
                )
                if result is None:
                    raise RuntimeError("behavior action unexpectedly matched a command")
                reply = result.reply or ""
                if _is_provider_error_reply(services, ctx.locale, reply):
                    raise RuntimeError(f"provider failure surfaced as a classified reply: {reply}")
                trace = result.tool_trace or []
                after = await _behavior_snapshot(services, ctx)
                session = await services.battles.generator.get_current_session(ctx.chat_key)
                after["checks"] = list(session.skill_checks if session else [])
                rolled = _dice_rolled(trace)
                finding: dict[str, Any] = {}
                if "expect_roll" in turn:
                    if turn["expect_roll"]:
                        metrics.roll_required_cases += 1
                        if not rolled:
                            metrics.dice_first_misses += 1
                            finding["dice_first_miss"] = True
                    else:
                        metrics.no_roll_cases += 1
                        if rolled:
                            metrics.over_roll_false_positives += 1
                            finding["over_roll_false_positive"] = True
                if "actor_expectation" in turn:
                    metrics.actor_cases += 1
                    actor_snapshot = {
                        "checks": after["checks"][len(before["checks"]) :],
                        "events": after["events"],
                    }
                    compliant, actor_reason = _score_actor(turn, trace, actor_snapshot)
                    if compliant:
                        metrics.actor_compliant += 1
                    else:
                        finding["actor_noncompliance"] = actor_reason
                # Score every turn. Fixture expectations pin deliberate state
                # mutations; the generic scorer also catches explicit HP/scene/
                # focus/clock claims made on any other narration.
                metrics.state_cases += 1
                claims = list((turn.get("state_expectation") or {}).get("reply_claims", []))
                metrics.state_required_claims += len(claims)
                metrics.state_present_claims += sum(
                    _reply_asserts_claim(reply, str(claim)) for claim in claims
                )
                consistent, failures = _score_state(turn, reply, after)
                if not consistent:
                    metrics.state_divergences += 1
                    finding["state_divergence"] = failures
                event_expectation = turn.get("event_expectation")
                if event_expectation:
                    event_groups[str(event_expectation["group"])] = dict(event_expectation)
                initiative_expectation = turn.get("initiative_expectation")
                if initiative_expectation:
                    next_entries = [
                        entry
                        for entry in trace
                        if entry.get("name") == "initiative_tracker"
                        and (entry.get("arguments") or {}).get("action") == "next"
                    ]
                    suppressed = [
                        entry
                        for entry in next_entries
                        if "already" in str(entry.get("result", "")).lower()
                        or "已经" in str(entry.get("result", ""))
                        or "suppressed" in str(entry.get("result", "")).lower()
                        or "抑制" in str(entry.get("result", ""))
                    ]
                    metrics.initiative_suppression_observations.append(
                        {
                            "turn_id": turn_id,
                            "action": str(turn["action"])[:300],
                            "reply": reply[:300],
                            "expected_advances": int(initiative_expectation["expected_advances"]),
                            "legitimate_multi_advance": bool(initiative_expectation.get("legitimate", False)),
                            "next_calls": len(next_entries),
                            "suppressed_calls": len(suppressed),
                            "trace_excerpt": [
                                {"arguments": entry.get("arguments"), "result": str(entry.get("result", ""))[:180]}
                                for entry in next_entries
                            ],
                        }
                    )
                record = {
                    "turn_id": turn_id,
                    "action": turn["action"],
                    "reply": reply,
                    "tool_trace": trace,
                    "state_before": before,
                    "state_after": after,
                    "finding": finding,
                }
                records.append(record)
                recorder.emit("behavior_turn", **record)
            except Exception as exc:
                metrics.errors += 1
                error_record = {
                    "turn_id": turn_id,
                    "action": turn["action"],
                    "error": f"{type(exc).__name__}: {exc}",
                    "traceback": traceback.format_exc()[-1500:],
                }
                records.append(error_record)
                recorder.emit("BEHAVIOR_TURN_ERROR", **error_record)
        final_snapshot = await _behavior_snapshot(services, ctx)
        for group, expectation in event_groups.items():
            metrics.event_groups += 1
            direct = [
                description
                for description in final_snapshot["events"]
                if _event_matches_expectation(description, expectation)
            ]
            # Once a fixture-grounded direct match anchors the milestone, include
            # conservative semantic paraphrases too. This prevents a duplicate
            # from disappearing merely because it used an allowed synonym.
            matching = list(direct)
            for description in final_snapshot["events"]:
                if description in matching:
                    continue
                if any(
                    _event_description_is_semantic_duplicate(description, anchor)
                    for anchor in direct
                ):
                    matching.append(description)
            if matching:
                metrics.recorded_event_groups += 1
            if len(matching) > int(expectation.get("max_records", 1)):
                metrics.duplicated_event_groups += 1
            recorder.emit(
                "behavior_event_group",
                episode=episode["id"],
                group=group,
                matching_events=matching,
                max_records=int(expectation.get("max_records", 1)),
            )
    return metrics, records


async def _build_behavior_services(
    *,
    mode: str,
    fixture: dict[str, Any],
    credentials_db: str,
    provider: str,
    model: str,
    reasoning_effort: str,
) -> tuple[Any, tempfile.TemporaryDirectory | None, MeteredLLM]:
    settings = get_settings().model_copy(deep=True)
    settings.llm = settings.llm.model_copy(
        update={
            "provider": provider,
            "chat_model": model,
            "analysis_model": model,
            "npc_model": model,
            "api_key": "",
            "base_url": "",
            "reasoning_effort": reasoning_effort,
        }
    )
    if mode == "smoke":
        services = build_services(
            settings,
            llm=BehaviorSmokeLLM(fixture),
            embeddings=LocalEmbeddings(64),
        )
        meter = _meter_services(services)
        return services, None, meter

    if not credentials_db:
        raise ValueError("live behavioral mode requires --credentials-db")
    try:
        source_uri = f"file:{Path(credentials_db).resolve()}?mode=ro"
        with sqlite3.connect(source_uri, uri=True) as source:
            row = source.execute(
                "SELECT value FROM kv WHERE user_key = '' AND store_key = ?",
                (CREDENTIALS_KEY,),
            ).fetchone()
        credentials = row[0] if row else None
    except sqlite3.Error as exc:
        raise ValueError("credentials database could not be read") from exc
    if not credentials:
        raise ValueError("credentials database has no provider credential book")

    # Copy only the requested provider into the disposable DB. This minimizes
    # secret exposure and prevents an unrelated provider credential from
    # appearing in an eval artifact if the temp directory is inspected.
    try:
        credential_book = json.loads(credentials)
    except (json.JSONDecodeError, TypeError, ValueError) as exc:
        raise ValueError("credentials database has an invalid provider credential book") from exc
    provider_key = provider.casefold()
    canonical_key = canonical_subscription_provider(provider_key) or provider_key
    selected = credential_book.get(canonical_key) if isinstance(credential_book, dict) else None
    if not isinstance(selected, dict):
        raise ValueError(f"credentials database has no credential for provider {canonical_key!r}")
    credentials = json.dumps({canonical_key: selected})

    temporary = tempfile.TemporaryDirectory(prefix="loreweaver-behavior-eval-")
    eval_store = Store(Path(temporary.name) / "eval.db")
    await eval_store.set(store_key=CREDENTIALS_KEY, value=credentials)
    await eval_store.set(
        store_key=DEFAULT_KEY,
        value=json.dumps(
            {
                "provider": provider,
                "chat_model": model,
                "analysis_model": model,
                "npc_model": model,
                "api_key": "",
                "base_url": "",
            }
        ),
    )
    services = build_services(
        settings,
        store=eval_store,
        embeddings=LocalEmbeddings(64),
    )
    meter = _meter_services(services)
    return services, temporary, meter


def _git_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def write_behavior_summary_json(
    path: Path,
    *,
    metrics: BehaviorMetrics,
    thresholds: BehaviorThresholds,
    passed: bool,
    reasons: list[str],
    metadata: dict[str, Any],
    usage: UsageTotals,
    records: list[dict[str, Any]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        **metadata,
        "passed": passed,
        "reasons": reasons,
        "counts": asdict(metrics),
        "rates": metrics.rates(),
        "thresholds": asdict(thresholds),
        "usage": asdict(usage),
        "records": records,
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


# =============================================================================
# Play-test harness
# =============================================================================


class Recorder:
    """Structured JSONL sink + the running `RedlineMetrics` for the end-of-run report."""

    def __init__(self, path: Path, *, append: bool = True):
        self.path = path
        path.parent.mkdir(parents=True, exist_ok=True)
        self.fh = path.open("a" if append else "w", encoding="utf-8")
        self.metrics = RedlineMetrics()

    def emit(self, kind: str, **fields):
        rec = {"kind": kind, **fields}
        self.fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        self.fh.flush()

    def close(self):
        self.fh.close()


async def _gen_player_action(services, archetype_desc: str, name: str, recent: str) -> str:
    prompt = (
        f"You are {name}, {archetype_desc}, a PLAYER (not the Keeper) at a Call of Cthulhu table. "
        f"Recent play:\n{recent[-1800:]}\n\n"
        "If the Keeper just asked you to roll or make a check (e.g. it wrote '.ra 侦查', 'make a Spot Hidden "
        "check', or 'roll SAN'), reply with ONLY the exact dice command: '.ra <skill>' for a skill check, "
        "'.sc 1/1d6' for a sanity check, or '.r <expr>' for a raw roll (use the skill the Keeper named). "
        "Otherwise, say in ONE short first-person line what your character does or says next (be concrete and in "
        "character). Roughly every other turn, ATTEMPT something that plausibly warrants a skill check — search, "
        "climb, sneak, persuade, listen at a door — so checks actually happen; act only on people, places and "
        "objects present in the recent play, never inventing new ones. Output only the single line or command."
    )
    try:
        r = await services.llm.chat([{"role": "user", "content": prompt}], temperature=0.9)
        line = (r.content or "").strip().splitlines()
        return (line[0] if line else "").strip()[:240] or "I look around and stay alert."
    except Exception:
        return "I look around and stay alert."


async def _setup(services, ts, module_path: Path, companion_path: Path | None, chat_key: str, rec: Recorder):
    fs = LocalFs(str(ROOT))
    kp_ctx = AgentCtx(chat_key=chat_key, user_id="playtest:setup", platform="cli", locale="en", fs=fs)
    # seed + analyze the module via the real Keeper LLM
    text = module_path.read_text(encoding="utf-8")
    await services.store.set(store_key=f"module_fulltext.{chat_key}", value=text)
    await services.module_init.initialize(chat_key)
    status = await services.store.get(store_key=f"module_init_status.{chat_key}")
    keeper_pool = (await services.store.get(store_key=f"module_keeper_pool.{chat_key}")) or ""
    rec.emit("setup", chat_key=chat_key, module=str(module_path), module_status=status,
             keeper_pool_chars=len(keeper_pool))
    # import the ST companion card (parse -> rule-legal sheet -> player_companion + character_book->worldbook)
    companion_name = None
    if companion_path is not None and companion_path.exists():
        try:
            card = parse_card_file(companion_path)
            res = await ts.dispatch("import_character", kp_ctx,
                                    {"file_path": str(companion_path), "system": "coc7", "as_": "companion"})
            companion_name = card.name
            rec.emit("companion_import", name=card.name, book_entries=len(card.character_book), result=str(res)[:200])
        except Exception as exc:
            rec.emit("companion_import_error", error=f"{type(exc).__name__}: {exc}")
    return keeper_pool, companion_name


async def run_session(
    services, ts, router, hub, module_path, companion_path, players, turns, sidx, rec: Recorder, secret_concepts: list[str]
):
    chat_key = f"playtest:s{sidx}"
    keeper_pool, companion_name = await _setup(services, ts, module_path, companion_path, chat_key, rec)
    secret_snippets = extract_secret_snippets(keeper_pool)

    fs = LocalFs(str(ROOT))
    pcs = [(f"{a[0]}-{sidx}", a[1]) for a in ARCHETYPES[:players]]
    for pname, _ in pcs:
        try:
            await ts.dispatch("create_character",
                              AgentCtx(chat_key=chat_key, user_id=f"pc:{pname}", platform="cli", locale="en", fs=fs),
                              {"name": pname, "system": "coc7"})
        except Exception as exc:
            rec.metrics.errors += 1
            rec.emit("create_char_error", player=pname, error=str(exc))

    transcript: list[str] = []
    for turn in range(1, turns + 1):
        for pname, adesc in pcs:
            ctx = AgentCtx(chat_key=chat_key, user_id=f"pc:{pname}", platform="cli", locale="en", fs=fs)
            action = await _gen_player_action(services, adesc, pname, "\n".join(transcript[-16:]))
            transcript.append(f">>> {pname}: {action}")
            try:
                res = await run_turn(hub, services, ctx, action, command_router=router, toolset=ts, actor_name=pname)
                reply = getattr(res, "reply", "") or ""
                if _is_provider_error_reply(services, ctx.locale, reply):
                    raise RuntimeError(f"provider failure surfaced as a classified reply: {reply}")
                tool_trace = getattr(res, "tool_trace", []) or []
                tools = [t.get("name") for t in tool_trace]
                transcript.append(f"[KP] {reply[:400]}")
                outcome = rec.metrics.record_turn(
                    reply=reply, action=action, tool_trace=tool_trace,
                    secret_snippets=secret_snippets, secret_concepts=secret_concepts,
                )
                if outcome["literal_leak"] or outcome["paraphrase_leak"]:
                    rec.emit("LEAK", session=sidx, turn=turn, player=pname, reply=reply[:300],
                             literal_secret=(outcome["literal_leak"] or "")[:120],
                             paraphrase_concept=outcome["paraphrase_leak"])
                if outcome["missed_roll"]:
                    rec.emit("DICE_MISS", session=sidx, turn=turn, player=pname, action=action, reply=reply[:300])
                if not reply.strip():
                    rec.emit("empty_kp_reply", session=sidx, turn=turn, player=pname, tools=tools)
                rec.emit("turn", session=sidx, turn=turn, player=pname, archetype=adesc.split(",")[0],
                         action=action, kp_reply=reply, tools=tools,
                         leaked=bool(outcome["literal_leak"] or outcome["paraphrase_leak"]),
                         missed_roll=outcome["missed_roll"])
            except Exception as exc:
                rec.metrics.errors += 1
                rec.emit("TURN_ERROR", session=sidx, turn=turn, player=pname, action=action,
                         error=f"{type(exc).__name__}: {exc}", trace=traceback.format_exc()[-1200:])
    # export the session report (exercises the export feature too)
    try:
        rep = await ts.dispatch("export_report",
                                AgentCtx(chat_key=chat_key, user_id="pc:"+pcs[0][0], platform="cli", locale="en", fs=fs),
                                {"detailed": True})
        rec.emit("session_report", session=sidx, chars=len(str(rep)))
    except Exception as exc:
        rec.metrics.errors += 1
        rec.emit("session_report_error", session=sidx, error=str(exc))


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--suite", choices=("generated", "behavioral"), default="generated")
    ap.add_argument("--mode", choices=("smoke", "live"), default="live",
                    help="behavioral suite only: deterministic FakeLLM smoke or real subscription model")
    ap.add_argument("--scenarios", default="tests/fixtures/behavioral_eval_scenarios.json",
                    help="behavioral suite fixture with fixed roll/no-roll ground truth")
    ap.add_argument("--run-label", default="run", help="label stored in behavioral artifacts")
    ap.add_argument("--credentials-db", default="",
                    help="read-only credential source for behavioral live mode; copied into an isolated temp DB")
    ap.add_argument("--provider", default="chatgpt", help="behavioral live provider")
    ap.add_argument("--model", default="gpt-5.6-sol", help="behavioral live model")
    ap.add_argument("--reasoning-effort", default="medium", help="behavioral live reasoning effort")
    ap.add_argument("--max-over-roll-fp-rate", type=float, default=0.10)
    ap.add_argument("--max-behavior-dice-miss-rate", type=float, default=0.0)
    ap.add_argument("--max-state-divergence-rate", type=float, default=1.0)
    ap.add_argument("--min-actor-compliance-rate", type=float, default=0.95)
    ap.add_argument("--max-event-dup-rate", type=float, default=0.0)
    ap.add_argument("--min-event-recording-coverage", type=float, default=1.0)
    ap.add_argument("--baseline-summary", default="",
                    help="optional behavioral baseline; requires final state divergence to improve by >=1 case")
    ap.add_argument("--module", default="tests/fixtures/module_en.txt")
    ap.add_argument("--companion", default="cards/companion_shenmo.json")
    ap.add_argument("--players", type=int, default=2)
    ap.add_argument("--turns", type=int, default=6)
    ap.add_argument("--sessions", type=int, default=1)
    ap.add_argument("--log", default="playtest/run.jsonl")
    ap.add_argument("--secret-concepts", default="",
                     help="comma-separated paraphrase-leak sentinel phrases specific to --module")
    ap.add_argument("--secret-concepts-file", default="",
                     help="path to a file with one paraphrase sentinel phrase per line (merged with --secret-concepts)")
    ap.add_argument("--max-leak-rate", type=float, default=0.0,
                     help="gate: max allowed fraction of turns with a literal-or-paraphrase leak")
    ap.add_argument("--max-dice-miss-rate", type=float, default=0.2,
                     help="gate: max allowed fraction of checkable turns where no dice tool fired")
    ap.add_argument("--min-checkable-turns", type=int, default=1,
                     help="gate: below this many checkable turns, dice-miss rate is not gated (too little signal)")
    ap.add_argument("--gate", action="store_true",
                     help="exit non-zero (after printing the report) if thresholds are violated -- for CI")
    ap.add_argument("--summary-json", default="", help="optional path to write a machine-readable JSON summary")
    args = ap.parse_args()

    if args.suite == "behavioral":
        fixture_path = (ROOT / args.scenarios).resolve()
        fixture = load_behavior_fixture(fixture_path)
        fixture_bytes = fixture_path.read_bytes()
        thresholds = BehaviorThresholds(
            max_over_roll_fp_rate=args.max_over_roll_fp_rate,
            max_dice_first_miss_rate=args.max_behavior_dice_miss_rate,
            max_state_divergence_rate=args.max_state_divergence_rate,
            min_actor_compliance_rate=args.min_actor_compliance_rate,
            max_event_dup_rate=args.max_event_dup_rate,
            min_event_recording_coverage=args.min_event_recording_coverage,
        )
        if args.baseline_summary:
            baseline = json.loads((ROOT / args.baseline_summary).read_text(encoding="utf-8"))
            baseline_rate = float(baseline["rates"]["state_divergence_rate"])
            state_cases = len(_fixture_turns(fixture))
            improvement_target = max(0.0, baseline_rate - (1 / state_cases if state_cases else 0.0))
            thresholds.max_state_divergence_rate = min(
                thresholds.max_state_divergence_rate,
                improvement_target,
            )

        services = None
        temporary = None
        rec = Recorder((ROOT / args.log).resolve(), append=False)
        try:
            services, temporary, meter = await _build_behavior_services(
                mode=args.mode,
                fixture=fixture,
                credentials_db=args.credentials_db,
                provider=args.provider,
                model=args.model,
                reasoning_effort=args.reasoning_effort,
            )
            metadata = {
                "name": "playtest-behavioral",
                "run_label": args.run_label,
                "at": datetime.now().isoformat(timespec="seconds"),
                "git_sha": _git_sha(),
                "fixture": str(fixture_path.relative_to(ROOT)),
                "fixture_version": fixture["version"],
                "fixture_sha256": hashlib.sha256(fixture_bytes).hexdigest(),
                "mode": args.mode,
                "provider": args.provider if args.mode == "live" else "fake",
                "model": args.model if args.mode == "live" else "BehaviorSmokeLLM",
                "reasoning_effort": args.reasoning_effort if args.mode == "live" else "",
            }
            rec.emit("behavior_run_start", **metadata, thresholds=asdict(thresholds))
            metrics, records = await run_behavior_suite(services, fixture, rec)
            passed, reasons = evaluate_behavior_gate(metrics, thresholds)
            rec.emit(
                "behavior_run_end",
                passed=passed,
                reasons=reasons,
                counts=asdict(metrics),
                rates=metrics.rates(),
                usage=asdict(meter.usage),
            )
        finally:
            rec.close()
            if services is not None:
                services.store.close()
            if temporary is not None:
                temporary.cleanup()

        report = render_behavior_report(metrics, thresholds, passed, reasons)
        print(report)
        print(f"usage: calls={meter.usage.calls} total_tokens={meter.usage.total_tokens}")
        print(f"log -> {args.log}")
        if args.summary_json:
            write_behavior_summary_json(
                (ROOT / args.summary_json).resolve(),
                metrics=metrics,
                thresholds=thresholds,
                passed=passed,
                reasons=reasons,
                metadata=metadata,
                usage=meter.usage,
                records=records,
            )
        if args.gate and not passed:
            sys.exit(1)
        return

    secret_concepts = parse_secret_concepts(args.secret_concepts, args.secret_concepts_file)
    thresholds = GateThresholds(
        max_leak_rate=args.max_leak_rate,
        max_dice_miss_rate=args.max_dice_miss_rate,
        min_checkable_turns=args.min_checkable_turns,
    )

    temporary = None
    if args.credentials_db:
        services, temporary, meter = await _build_behavior_services(
            mode="live",
            fixture={"version": 1, "episodes": []},
            credentials_db=args.credentials_db,
            provider=args.provider,
            model=args.model,
            reasoning_effort=args.reasoning_effort,
        )
        settings = services.settings
    else:
        settings = get_settings()
        services = build_services(settings, embeddings=LocalEmbeddings(64))
        meter = _meter_services(services)
    ts = build_kp_toolset(services)
    router = CommandRouter(services)
    hub = RoomHub()
    rec = Recorder(ROOT / args.log)
    rec.emit("run_start", at=datetime.now().isoformat(timespec="seconds"),
             provider=settings.llm.provider, model=settings.llm.chat_model,
             module=args.module, players=args.players, turns=args.turns, sessions=args.sessions,
             secret_concepts=secret_concepts, thresholds=asdict(thresholds))
    module_path = (ROOT / args.module)
    companion_path = (ROOT / args.companion) if args.companion else None
    for sidx in range(1, args.sessions + 1):
        try:
            await run_session(services, ts, router, hub, module_path, companion_path, args.players, args.turns,
                              sidx, rec, secret_concepts)
        except Exception as exc:
            rec.metrics.errors += 1
            rec.emit("SESSION_ERROR", session=sidx, error=f"{type(exc).__name__}: {exc}",
                     trace=traceback.format_exc()[-1500:])
    rec.emit("run_end", turns=rec.metrics.turns, errors=rec.metrics.errors, leak_turns=rec.metrics.leak_turns,
             empty_kp=rec.metrics.empty_kp, missed_roll_turns=rec.metrics.missed_roll_turns,
             checkable_turns=rec.metrics.checkable_turns, usage=asdict(meter.usage))
    rec.close()

    passed, reasons = evaluate_gate(rec.metrics, thresholds)
    report = render_report("playtest", rec.metrics, thresholds, passed, reasons)
    print(report)
    print(f"usage: calls={meter.usage.calls} total_tokens={meter.usage.total_tokens}")
    print(f"log -> {args.log}")
    if args.summary_json:
        write_summary_json(ROOT / args.summary_json, "playtest", rec.metrics, thresholds, passed, reasons, meter.usage)
    services.store.close()
    if temporary is not None:
        temporary.cleanup()
    if args.gate and not passed:
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
