"""Headless play-test harness for Loreweaver.

Runs one or more full sessions against the REAL Keeper (whatever TRPG_LLM__* in
.env points at -- DeepSeek by default) driving the real turn pipeline (real
seeded-free dice, real tools, real companion actor), with simulated players whose
actions are generated by the same cheap LLM. Everything is logged to a structured
JSONL file for later analysis (an Opus pass reads it, finds bugs/leaks/rule
violations, and fixes them). Per-turn exceptions are caught + logged as findings so
one bad turn never kills the run.

Usage:
  .venv/bin/python scripts/playtest.py \
      --module modules/shuxue.md --companion cards/companion_shenmo.json \
      --players 2 --turns 8 --sessions 3 --log playtest/run.jsonl

Not committed data: modules/, cards/, playtest/ are gitignored.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
import traceback
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
except Exception:  # pragma: no cover - dotenv always present in this project
    pass

from agent.context import AgentCtx, LocalFs  # noqa: E402
from agent.kp_tools import build_kp_toolset  # noqa: E402
from agent.services import build_services  # noqa: E402
from core.charcard import parse_card_file  # noqa: E402
from gateway.commands import CommandRouter  # noqa: E402
from gateway.hub import RoomHub  # noqa: E402
from gateway.turn import run_turn  # noqa: E402
from infra.config import get_settings  # noqa: E402
from infra.embeddings import LocalEmbeddings  # noqa: E402

# Player archetypes -- varied behaviour surfaces different KP/engine paths.
ARCHETYPES = [
    ("Cautious", "a careful, methodical investigator who searches, asks questions, and rolls before acting"),
    ("Reckless", "a headstrong investigator who charges in, provokes NPCs, and tries risky physical actions"),
    ("Social", "a smooth talker who leans on persuade/fast-talk/charm and interrogates NPCs"),
    ("Scholar", "a bookish investigator who studies clues, cites lore, and wants library/occult checks"),
    ("Paranoid", "a suspicious investigator who distrusts NPCs, checks for traps, and second-guesses everything"),
]


class Recorder:
    """Structured JSONL sink + in-memory tallies for the end-of-run summary."""

    def __init__(self, path: Path):
        self.path = path
        path.parent.mkdir(parents=True, exist_ok=True)
        self.fh = path.open("a", encoding="utf-8")
        self.turns = 0
        self.errors = 0
        self.leaks = 0
        self.empty_kp = 0

    def emit(self, kind: str, **fields):
        rec = {"kind": kind, **fields}
        self.fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        self.fh.flush()

    def close(self):
        self.fh.close()


async def _gen_player_action(services, archetype_desc: str, name: str, recent: str) -> str:
    prompt = (
        f"You are {name}, {archetype_desc}, a PLAYER (not the Keeper) at a Call of Cthulhu table. "
        f"Recent play:\n{recent[-1800:]}\n\n"
        "If the Keeper just asked you to roll or make a check (e.g. it wrote '.ra 侦查', 'make a Spot Hidden "
        "check', or 'roll SAN'), reply with ONLY the exact dice command: '.ra <skill>' for a skill check, "
        "'.sc 1/1d6' for a sanity check, or '.r <expr>' for a raw roll (use the skill the Keeper named). "
        "Otherwise, say in ONE short first-person line what your character does or says next (be concrete and in "
        "character; you may attempt something that warrants a check). Output only the single line or command."
    )
    try:
        r = await services.llm.chat([{"role": "user", "content": prompt}], temperature=0.9)
        line = (r.content or "").strip().splitlines()
        return (line[0] if line else "").strip()[:240] or "I look around and stay alert."
    except Exception:
        return "I look around and stay alert."


async def _setup(services, ts, module_path: Path, companion_path: Path | None, chat_key: str, rec: Recorder):
    fs = LocalFs(str(ROOT))
    kp_ctx = AgentCtx(chat_key=chat_key, user_id="playtest:setup", platform="cli", locale="en", fs=fs)
    # seed + analyze the module via the real Keeper LLM
    text = module_path.read_text(encoding="utf-8")
    await services.store.set(store_key=f"module_fulltext.{chat_key}", value=text)
    await services.module_init.initialize(chat_key)
    status = await services.store.get(store_key=f"module_init_status.{chat_key}")
    keeper_pool = (await services.store.get(store_key=f"module_keeper_pool.{chat_key}")) or ""
    rec.emit("setup", chat_key=chat_key, module=str(module_path), module_status=status,
             keeper_pool_chars=len(keeper_pool))
    # import the ST companion card (parse -> rule-legal sheet -> player_companion + character_book->worldbook)
    companion_name = None
    if companion_path is not None and companion_path.exists():
        try:
            card = parse_card_file(companion_path)
            res = await ts.dispatch("import_character", kp_ctx,
                                    {"file_path": str(companion_path), "system": "coc7", "as_": "companion"})
            companion_name = card.name
            rec.emit("companion_import", name=card.name, book_entries=len(card.character_book), result=str(res)[:200])
        except Exception as exc:
            rec.emit("companion_import_error", error=f"{type(exc).__name__}: {exc}")
    return keeper_pool, companion_name


async def run_session(services, ts, router, hub, module_path, companion_path, players, turns, sidx, rec: Recorder):
    chat_key = f"playtest:s{sidx}"
    keeper_pool, companion_name = await _setup(services, ts, module_path, companion_path, chat_key, rec)
    # a rough secret sentinel set: long-ish keeper-only lines the KP must not echo verbatim to players
    secret_lines = [ln.strip() for ln in keeper_pool.splitlines() if len(ln.strip()) > 40][:40]

    fs = LocalFs(str(ROOT))
    pcs = [(f"{a[0]}-{sidx}", a[1]) for a in ARCHETYPES[:players]]
    for pname, _ in pcs:
        try:
            await ts.dispatch("create_character",
                              AgentCtx(chat_key=chat_key, user_id=f"pc:{pname}", platform="cli", locale="en", fs=fs),
                              {"name": pname, "system": "coc7"})
        except Exception as exc:
            rec.emit("create_char_error", player=pname, error=str(exc))

    transcript: list[str] = []
    for turn in range(1, turns + 1):
        for pname, adesc in pcs:
            ctx = AgentCtx(chat_key=chat_key, user_id=f"pc:{pname}", platform="cli", locale="en", fs=fs)
            action = await _gen_player_action(services, adesc, pname, "\n".join(transcript[-16:]))
            transcript.append(f">>> {pname}: {action}")
            try:
                res = await run_turn(hub, services, ctx, action, command_router=router, toolset=ts, actor_name=pname)
                reply = getattr(res, "reply", "") or ""
                tools = [t.get("name") for t in getattr(res, "tool_trace", [])]
                transcript.append(f"[KP] {reply[:400]}")
                # leak check: did a keeper-only secret line appear verbatim in the player-facing reply?
                leaked = next((s for s in secret_lines if s and s in reply), None)
                if leaked:
                    rec.leaks += 1
                    rec.emit("LEAK", session=sidx, turn=turn, player=pname, secret=leaked[:120], reply=reply[:300])
                if not reply.strip():
                    rec.empty_kp += 1
                    rec.emit("empty_kp_reply", session=sidx, turn=turn, player=pname, tools=tools)
                rec.turns += 1
                rec.emit("turn", session=sidx, turn=turn, player=pname, archetype=adesc.split(",")[0],
                         action=action, kp_reply=reply, tools=tools, leaked=bool(leaked))
            except Exception as exc:
                rec.errors += 1
                rec.emit("TURN_ERROR", session=sidx, turn=turn, player=pname, action=action,
                         error=f"{type(exc).__name__}: {exc}", trace=traceback.format_exc()[-1200:])
    # export the session report (exercises the export feature too)
    try:
        rep = await ts.dispatch("export_report",
                                AgentCtx(chat_key=chat_key, user_id="pc:"+pcs[0][0], platform="cli", locale="en", fs=fs),
                                {"detailed": True})
        rec.emit("session_report", session=sidx, chars=len(str(rep)))
    except Exception as exc:
        rec.emit("session_report_error", session=sidx, error=str(exc))


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--module", default="tests/fixtures/module_en.txt")
    ap.add_argument("--companion", default="cards/companion_shenmo.json")
    ap.add_argument("--players", type=int, default=2)
    ap.add_argument("--turns", type=int, default=6)
    ap.add_argument("--sessions", type=int, default=1)
    ap.add_argument("--log", default="playtest/run.jsonl")
    args = ap.parse_args()

    settings = get_settings()
    services = build_services(settings, embeddings=LocalEmbeddings(64))
    ts = build_kp_toolset(services)
    router = CommandRouter(services)
    hub = RoomHub()
    rec = Recorder(ROOT / args.log)
    rec.emit("run_start", at=datetime.now().isoformat(timespec="seconds"),
             provider=settings.llm.provider, model=settings.llm.chat_model,
             module=args.module, players=args.players, turns=args.turns, sessions=args.sessions)
    module_path = (ROOT / args.module)
    companion_path = (ROOT / args.companion) if args.companion else None
    for sidx in range(1, args.sessions + 1):
        try:
            await run_session(services, ts, router, hub, module_path, companion_path, args.players, args.turns, sidx, rec)
        except Exception as exc:
            rec.emit("SESSION_ERROR", session=sidx, error=f"{type(exc).__name__}: {exc}",
                     trace=traceback.format_exc()[-1500:])
    rec.emit("run_end", turns=rec.turns, errors=rec.errors, leaks=rec.leaks, empty_kp=rec.empty_kp)
    rec.close()
    print(f"playtest done: {rec.turns} turns | {rec.errors} errors | {rec.leaks} leaks | "
          f"{rec.empty_kp} empty-KP | log -> {args.log}")


if __name__ == "__main__":
    asyncio.run(main())
