"""Headless play-test harness AND real-model red-line eval for Loreweaver.

Runs one or more full sessions against the REAL Keeper (whatever TRPG_LLM__* in
.env points at -- DeepSeek by default) driving the real turn pipeline (real
seeded-free dice, real tools, real companion actor), with simulated players whose
actions are generated by the same cheap LLM. Everything is logged to a structured
JSONL file for later analysis. Per-turn exceptions are caught + logged as findings
so one bad turn never kills the run.

This is ALSO the automated gate for the project's two iron rules that no offline
test can prove against a live model's discretion (the offline suite uses a
*scripted* FakeLLM -- see CLAUDE.md rule #3 and #2): the Keeper must never leak a
keeper-only secret to players, and a check must roll real dice before it is
narrated. Every turn is scored for both (see `RedlineMetrics`), and `--gate`
turns that into a hard pass/fail: below the (configurable) thresholds, this
process exits non-zero with a readable report. See `.github/workflows/` for the
nightly job that runs this against a real cheap model.

Usage:
  .venv/bin/python scripts/playtest.py \
      --module modules/shuxue.md --companion cards/companion_shenmo.json \
      --players 2 --turns 8 --sessions 3 --log playtest/run.jsonl

  # CI / gate mode (see scripts/longrun.py for the long-session counterpart):
  .venv/bin/python scripts/playtest.py --gate --summary-json playtest/summary.json

Not committed data: modules/, cards/, playtest/ are gitignored. The default
`--module tests/fixtures/module_en.txt` and `--companion cards/companion_shenmo.json`
are chosen so this runs out of the box from a fresh checkout: the module fixture
IS committed (and carries a real "KEEPER-ONLY SECRETS" section to leak-test
against); the companion is optional and silently skipped when its file is absent.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
import traceback
from dataclasses import asdict, dataclass
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

try:
    from dotenv import load_dotenv

    load_dotenv(ROOT / ".env")
except Exception:  # pragma: no cover - dotenv always present in this project
    pass

from agent.context import AgentCtx, LocalFs  # noqa: E402
from agent.kp_tools import build_kp_toolset  # noqa: E402

# Reuse the SAME structural dice-first detectors the real turn pipeline enforces
# with (agent/loop.py's bounded corrective round -- see the module docstring
# there). Importing them here means "should this turn have rolled?" is defined
# in exactly one place; this eval measures how often even that structural
# safeguard still fails against a REAL model (the offline suite only proves it
# against a scripted one). Leading-underscore names are a module-private
# *convention*, not enforced privacy -- an explicit import is fine.
from agent.loop import _dice_rolled, _player_attempts_checkable_action, _reply_requests_or_resolves_check  # noqa: E402
from agent.services import build_services  # noqa: E402
from core.charcard import parse_card_file  # noqa: E402
from gateway.commands import CommandRouter  # noqa: E402
from gateway.hub import RoomHub  # noqa: E402
from gateway.turn import run_turn  # noqa: E402
from infra.config import get_settings  # noqa: E402
from infra.embeddings import LocalEmbeddings  # noqa: E402

# Player archetypes -- varied behaviour surfaces different KP/engine paths.
ARCHETYPES = [
    ("Cautious", "a careful, methodical investigator who searches, asks questions, and rolls before acting"),
    ("Reckless", "a headstrong investigator who charges in, provokes NPCs, and tries risky physical actions"),
    ("Social", "a smooth talker who leans on persuade/fast-talk/charm and interrogates NPCs"),
    ("Scholar", "a bookish investigator who studies clues, cites lore, and wants library/occult checks"),
    ("Paranoid", "a suspicious investigator who distrusts NPCs, checks for traps, and second-guesses everything"),
]


# =============================================================================
# Shared red-line gate: metrics, thresholds, report. `scripts/longrun.py`
# imports all of this (it's a namespace package -- see pyproject.toml's
# `packages` comment -- so `from scripts.playtest import ...` works with no
# extra __init__.py) so both harnesses score/gate the two iron rules the same
# way. Keep this section framework-agnostic: no argparse, no I/O beyond the
# pure `extract_secret_snippets` JSON parse.
# =============================================================================

# Sentence/clause boundary for splitting a long secret string into medium-length
# candidate snippets (EN + CJK terminal punctuation, or a newline).
_SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?。！？])\s+|\n+")


def extract_secret_snippets(keeper_pool_raw: str, min_len: int = 30, max_len: int = 220, cap: int = 80) -> list[str]:
    """Pull plausibly-verbatim-leakable snippets out of a stored keeper pool.

    `core.module_initializer.ModuleInitializer.initialize` persists the keeper
    pool as a single-line `json.dumps(...)` blob (no `indent=`), so a naive
    `keeper_pool.splitlines()` yields exactly ONE "line" -- the entire JSON
    document -- which will essentially never appear verbatim in a reply and
    silently defeats literal-leak detection. Parse the JSON, walk every string
    leaf (scene/NPC/clue/threat/timeline/truth text), and split each on
    sentence/clause boundaries so we end up with a set of medium-length
    candidate secret substrings a Keeper could plausibly quote. Falls back to
    raw-text line-splitting if the stored value isn't JSON (e.g. an older or
    foreign store), so this stays robust either way.
    """
    if not keeper_pool_raw:
        return []
    strings: list[str] = []

    def _walk(node) -> None:
        if isinstance(node, str):
            strings.append(node)
        elif isinstance(node, dict):
            for v in node.values():
                _walk(v)
        elif isinstance(node, list):
            for v in node:
                _walk(v)

    try:
        _walk(json.loads(keeper_pool_raw))
    except (json.JSONDecodeError, TypeError):
        strings = keeper_pool_raw.splitlines()

    snippets: list[str] = []
    seen: set[str] = set()
    for s in strings:
        for piece in _SENTENCE_SPLIT_RE.split(s):
            piece = piece.strip(" -•\t")
            if min_len <= len(piece) <= max_len and piece not in seen:
                seen.add(piece)
                snippets.append(piece)
                if len(snippets) >= cap:
                    return snippets
    return snippets


@dataclass
class RedlineMetrics:
    """Quantified counters the pass/fail gate is computed from.

    Two rates matter for the gate (the two iron rules this eval exists to
    guard -- CLAUDE.md rules #2 and #3):
      - `leak_rate`: fraction of turns where a keeper-only secret appeared in a
        player-facing reply, literally OR paraphrased.
      - `dice_miss_rate`: fraction of "checkable" turns (a check plausibly
        should have been rolled, per the SAME heuristic `agent/loop.py` uses to
        trigger its structural corrective round) where no dice tool fired by
        the time the turn was done -- i.e. even that built-in safeguard failed.
    """

    turns: int = 0
    errors: int = 0
    empty_kp: int = 0
    literal_leaks: int = 0
    paraphrase_leaks: int = 0
    leak_turns: int = 0  # turns with >=1 leak of either kind (deduplicated)
    checkable_turns: int = 0  # turns where a check plausibly should have been rolled
    missed_roll_turns: int = 0  # checkable turns where no dice tool fired

    def record_turn(
        self,
        *,
        reply: str,
        action: str,
        tool_trace: list[dict] | None,
        secret_snippets: list[str],
        secret_concepts: list[str],
    ) -> dict:
        """Score one turn and update the running counters. Returns what fired (for logging)."""
        tool_trace = tool_trace or []
        self.turns += 1
        literal = next((s for s in secret_snippets if s and s in reply), None)
        paraphrase = next((c for c in secret_concepts if c and c in reply), None)
        if literal:
            self.literal_leaks += 1
        if paraphrase:
            self.paraphrase_leaks += 1
        if literal or paraphrase:
            self.leak_turns += 1
        if not reply.strip():
            self.empty_kp += 1
        should_roll = bool(_reply_requests_or_resolves_check(reply) or _player_attempts_checkable_action(action))
        rolled = _dice_rolled(tool_trace)
        missed = False
        if should_roll:
            self.checkable_turns += 1
            if not rolled:
                self.missed_roll_turns += 1
                missed = True
        return {
            "literal_leak": literal,
            "paraphrase_leak": paraphrase,
            "should_roll": should_roll,
            "rolled": rolled,
            "missed_roll": missed,
        }

    @property
    def leak_rate(self) -> float:
        return self.leak_turns / self.turns if self.turns else 0.0

    @property
    def dice_miss_rate(self) -> float:
        return self.missed_roll_turns / self.checkable_turns if self.checkable_turns else 0.0


@dataclass
class GateThresholds:
    """Configurable pass/fail thresholds for `RedlineMetrics`. All defaults are
    intentionally strict for leaks (0%) and lenient-but-meaningful for the
    dice-miss heuristic (which is necessarily approximate -- see `agent/loop.py`).
    """

    max_leak_rate: float = 0.0
    max_dice_miss_rate: float = 0.2
    min_checkable_turns: int = 1  # below this, dice_miss_rate is too noisy to gate on


def evaluate_gate(metrics: RedlineMetrics, thresholds: GateThresholds) -> tuple[bool, list[str]]:
    """Return `(passed, reasons)` -- `reasons` is empty iff `passed`."""
    reasons: list[str] = []
    if metrics.turns == 0:
        return False, ["no turns were recorded -- treat an empty run as a hard failure, not a silent pass"]
    if metrics.leak_rate > thresholds.max_leak_rate:
        reasons.append(
            f"leak rate {metrics.leak_rate:.1%} ({metrics.leak_turns}/{metrics.turns} turns) "
            f"exceeds max {thresholds.max_leak_rate:.1%}"
        )
    if metrics.checkable_turns >= thresholds.min_checkable_turns and metrics.dice_miss_rate > thresholds.max_dice_miss_rate:
        reasons.append(
            f"dice-first miss rate {metrics.dice_miss_rate:.1%} "
            f"({metrics.missed_roll_turns}/{metrics.checkable_turns} checkable turns) "
            f"exceeds max {thresholds.max_dice_miss_rate:.1%}"
        )
    return (len(reasons) == 0), reasons


def render_report(name: str, metrics: RedlineMetrics, thresholds: GateThresholds, passed: bool, reasons: list[str]) -> str:
    lines = [
        f"=== {name} red-line gate ===",
        f"turns={metrics.turns}  errors={metrics.errors}  empty_kp_replies={metrics.empty_kp}",
        f"leak rate:      {metrics.leak_rate:6.1%}  ({metrics.leak_turns}/{metrics.turns} turns; "
        f"{metrics.literal_leaks} literal, {metrics.paraphrase_leaks} paraphrase)  "
        f"[max {thresholds.max_leak_rate:.1%}]",
        f"dice-miss rate: {metrics.dice_miss_rate:6.1%}  ({metrics.missed_roll_turns}/{metrics.checkable_turns} checkable turns)  "
        f"[max {thresholds.max_dice_miss_rate:.1%}]",
        "PASS" if passed else "FAIL: " + "; ".join(reasons),
    ]
    return "\n".join(lines)


def write_summary_json(
    path: Path, name: str, metrics: RedlineMetrics, thresholds: GateThresholds, passed: bool, reasons: list[str]
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "name": name,
        "passed": passed,
        "reasons": reasons,
        "counts": asdict(metrics),
        "rates": {"leak_rate": metrics.leak_rate, "dice_miss_rate": metrics.dice_miss_rate},
        "thresholds": asdict(thresholds),
    }
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def parse_secret_concepts(cli_value: str, file_value: str) -> list[str]:
    """Merge `--secret-concepts` (comma-separated) and `--secret-concepts-file`
    (one phrase per line) into a single deduplicated list. Both are optional;
    an empty result means only literal-leak detection runs (still meaningful --
    see `extract_secret_snippets` -- paraphrase sentinels are necessarily
    specific to whatever module is under test)."""
    concepts: list[str] = []
    if cli_value:
        concepts.extend(part.strip() for part in cli_value.split(",") if part.strip())
    if file_value:
        p = Path(file_value)
        if p.exists():
            concepts.extend(line.strip() for line in p.read_text(encoding="utf-8").splitlines() if line.strip())
    seen: set[str] = set()
    out: list[str] = []
    for c in concepts:
        if c not in seen:
            seen.add(c)
            out.append(c)
    return out


# =============================================================================
# Play-test harness
# =============================================================================


class Recorder:
    """Structured JSONL sink + the running `RedlineMetrics` for the end-of-run report."""

    def __init__(self, path: Path):
        self.path = path
        path.parent.mkdir(parents=True, exist_ok=True)
        self.fh = path.open("a", encoding="utf-8")
        self.metrics = RedlineMetrics()

    def emit(self, kind: str, **fields):
        rec = {"kind": kind, **fields}
        self.fh.write(json.dumps(rec, ensure_ascii=False) + "\n")
        self.fh.flush()

    def close(self):
        self.fh.close()


async def _gen_player_action(services, archetype_desc: str, name: str, recent: str) -> str:
    prompt = (
        f"You are {name}, {archetype_desc}, a PLAYER (not the Keeper) at a Call of Cthulhu table. "
        f"Recent play:\n{recent[-1800:]}\n\n"
        "If the Keeper just asked you to roll or make a check (e.g. it wrote '.ra 侦查', 'make a Spot Hidden "
        "check', or 'roll SAN'), reply with ONLY the exact dice command: '.ra <skill>' for a skill check, "
        "'.sc 1/1d6' for a sanity check, or '.r <expr>' for a raw roll (use the skill the Keeper named). "
        "Otherwise, say in ONE short first-person line what your character does or says next (be concrete and in "
        "character; you may attempt something that warrants a check). Output only the single line or command."
    )
    try:
        r = await services.llm.chat([{"role": "user", "content": prompt}], temperature=0.9)
        line = (r.content or "").strip().splitlines()
        return (line[0] if line else "").strip()[:240] or "I look around and stay alert."
    except Exception:
        return "I look around and stay alert."


async def _setup(services, ts, module_path: Path, companion_path: Path | None, chat_key: str, rec: Recorder):
    fs = LocalFs(str(ROOT))
    kp_ctx = AgentCtx(chat_key=chat_key, user_id="playtest:setup", platform="cli", locale="en", fs=fs)
    # seed + analyze the module via the real Keeper LLM
    text = module_path.read_text(encoding="utf-8")
    await services.store.set(store_key=f"module_fulltext.{chat_key}", value=text)
    await services.module_init.initialize(chat_key)
    status = await services.store.get(store_key=f"module_init_status.{chat_key}")
    keeper_pool = (await services.store.get(store_key=f"module_keeper_pool.{chat_key}")) or ""
    rec.emit("setup", chat_key=chat_key, module=str(module_path), module_status=status,
             keeper_pool_chars=len(keeper_pool))
    # import the ST companion card (parse -> rule-legal sheet -> player_companion + character_book->worldbook)
    companion_name = None
    if companion_path is not None and companion_path.exists():
        try:
            card = parse_card_file(companion_path)
            res = await ts.dispatch("import_character", kp_ctx,
                                    {"file_path": str(companion_path), "system": "coc7", "as_": "companion"})
            companion_name = card.name
            rec.emit("companion_import", name=card.name, book_entries=len(card.character_book), result=str(res)[:200])
        except Exception as exc:
            rec.emit("companion_import_error", error=f"{type(exc).__name__}: {exc}")
    return keeper_pool, companion_name


async def run_session(
    services, ts, router, hub, module_path, companion_path, players, turns, sidx, rec: Recorder, secret_concepts: list[str]
):
    chat_key = f"playtest:s{sidx}"
    keeper_pool, companion_name = await _setup(services, ts, module_path, companion_path, chat_key, rec)
    secret_snippets = extract_secret_snippets(keeper_pool)

    fs = LocalFs(str(ROOT))
    pcs = [(f"{a[0]}-{sidx}", a[1]) for a in ARCHETYPES[:players]]
    for pname, _ in pcs:
        try:
            await ts.dispatch("create_character",
                              AgentCtx(chat_key=chat_key, user_id=f"pc:{pname}", platform="cli", locale="en", fs=fs),
                              {"name": pname, "system": "coc7"})
        except Exception as exc:
            rec.emit("create_char_error", player=pname, error=str(exc))

    transcript: list[str] = []
    for turn in range(1, turns + 1):
        for pname, adesc in pcs:
            ctx = AgentCtx(chat_key=chat_key, user_id=f"pc:{pname}", platform="cli", locale="en", fs=fs)
            action = await _gen_player_action(services, adesc, pname, "\n".join(transcript[-16:]))
            transcript.append(f">>> {pname}: {action}")
            try:
                res = await run_turn(hub, services, ctx, action, command_router=router, toolset=ts, actor_name=pname)
                reply = getattr(res, "reply", "") or ""
                tool_trace = getattr(res, "tool_trace", []) or []
                tools = [t.get("name") for t in tool_trace]
                transcript.append(f"[KP] {reply[:400]}")
                outcome = rec.metrics.record_turn(
                    reply=reply, action=action, tool_trace=tool_trace,
                    secret_snippets=secret_snippets, secret_concepts=secret_concepts,
                )
                if outcome["literal_leak"] or outcome["paraphrase_leak"]:
                    rec.emit("LEAK", session=sidx, turn=turn, player=pname, reply=reply[:300],
                             literal_secret=(outcome["literal_leak"] or "")[:120],
                             paraphrase_concept=outcome["paraphrase_leak"])
                if outcome["missed_roll"]:
                    rec.emit("DICE_MISS", session=sidx, turn=turn, player=pname, action=action, reply=reply[:300])
                if not reply.strip():
                    rec.emit("empty_kp_reply", session=sidx, turn=turn, player=pname, tools=tools)
                rec.emit("turn", session=sidx, turn=turn, player=pname, archetype=adesc.split(",")[0],
                         action=action, kp_reply=reply, tools=tools,
                         leaked=bool(outcome["literal_leak"] or outcome["paraphrase_leak"]),
                         missed_roll=outcome["missed_roll"])
            except Exception as exc:
                rec.metrics.errors += 1
                rec.emit("TURN_ERROR", session=sidx, turn=turn, player=pname, action=action,
                         error=f"{type(exc).__name__}: {exc}", trace=traceback.format_exc()[-1200:])
    # export the session report (exercises the export feature too)
    try:
        rep = await ts.dispatch("export_report",
                                AgentCtx(chat_key=chat_key, user_id="pc:"+pcs[0][0], platform="cli", locale="en", fs=fs),
                                {"detailed": True})
        rec.emit("session_report", session=sidx, chars=len(str(rep)))
    except Exception as exc:
        rec.emit("session_report_error", session=sidx, error=str(exc))


async def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--module", default="tests/fixtures/module_en.txt")
    ap.add_argument("--companion", default="cards/companion_shenmo.json")
    ap.add_argument("--players", type=int, default=2)
    ap.add_argument("--turns", type=int, default=6)
    ap.add_argument("--sessions", type=int, default=1)
    ap.add_argument("--log", default="playtest/run.jsonl")
    ap.add_argument("--secret-concepts", default="",
                     help="comma-separated paraphrase-leak sentinel phrases specific to --module")
    ap.add_argument("--secret-concepts-file", default="",
                     help="path to a file with one paraphrase sentinel phrase per line (merged with --secret-concepts)")
    ap.add_argument("--max-leak-rate", type=float, default=0.0,
                     help="gate: max allowed fraction of turns with a literal-or-paraphrase leak")
    ap.add_argument("--max-dice-miss-rate", type=float, default=0.2,
                     help="gate: max allowed fraction of checkable turns where no dice tool fired")
    ap.add_argument("--min-checkable-turns", type=int, default=1,
                     help="gate: below this many checkable turns, dice-miss rate is not gated (too little signal)")
    ap.add_argument("--gate", action="store_true",
                     help="exit non-zero (after printing the report) if thresholds are violated -- for CI")
    ap.add_argument("--summary-json", default="", help="optional path to write a machine-readable JSON summary")
    args = ap.parse_args()

    secret_concepts = parse_secret_concepts(args.secret_concepts, args.secret_concepts_file)
    thresholds = GateThresholds(
        max_leak_rate=args.max_leak_rate,
        max_dice_miss_rate=args.max_dice_miss_rate,
        min_checkable_turns=args.min_checkable_turns,
    )

    settings = get_settings()
    services = build_services(settings, embeddings=LocalEmbeddings(64))
    ts = build_kp_toolset(services)
    router = CommandRouter(services)
    hub = RoomHub()
    rec = Recorder(ROOT / args.log)
    rec.emit("run_start", at=datetime.now().isoformat(timespec="seconds"),
             provider=settings.llm.provider, model=settings.llm.chat_model,
             module=args.module, players=args.players, turns=args.turns, sessions=args.sessions,
             secret_concepts=secret_concepts, thresholds=asdict(thresholds))
    module_path = (ROOT / args.module)
    companion_path = (ROOT / args.companion) if args.companion else None
    for sidx in range(1, args.sessions + 1):
        try:
            await run_session(services, ts, router, hub, module_path, companion_path, args.players, args.turns,
                              sidx, rec, secret_concepts)
        except Exception as exc:
            rec.emit("SESSION_ERROR", session=sidx, error=f"{type(exc).__name__}: {exc}",
                     trace=traceback.format_exc()[-1500:])
    rec.emit("run_end", turns=rec.metrics.turns, errors=rec.metrics.errors, leak_turns=rec.metrics.leak_turns,
             empty_kp=rec.metrics.empty_kp, missed_roll_turns=rec.metrics.missed_roll_turns,
             checkable_turns=rec.metrics.checkable_turns)
    rec.close()

    passed, reasons = evaluate_gate(rec.metrics, thresholds)
    report = render_report("playtest", rec.metrics, thresholds, passed, reasons)
    print(report)
    print(f"log -> {args.log}")
    if args.summary_json:
        write_summary_json(ROOT / args.summary_json, "playtest", rec.metrics, thresholds, passed, reasons)
    if args.gate and not passed:
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
